version: '3.7'

services:
  postgres:
    image: postgres:12
    container_name: postgres 
    networks:
        - webnet
    env_file:
        - .env
    expose:
        - "${POSTGRES_PORT}"
    ports:
        - ${POSTGRES_PORT}:5432
    volumes:
        - pgdata:/var/lib/postgresql/data

  main:
    container_name: main
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - postgres
  
networks:
  webnet:
volumes:
  pgdata: